apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mks-oneclick-v3-1-40
  namespace: default
spec:
  encryptedData:
    registry_credentials: AQByV8OQui932LITkjmwksAO/3vQmoN5Dhetg8OH9SCLynwG2lOmzY7svvCAMXB+aKyVVxiwqiFn2I27FY0HOtZ1d0XNPXSB0CBmRiBguq17/ahpIZDSfEKHN7ixyjbVDKNGMZA5hVzESbAmRr0zHPSJrLdcuBPuYuXSz+ZmJAkhNYf2Qso0N37K8OMoZ7uUjQ4qLdAGyTX0DUW9J8ciBU+yLv4Nx1o1OlzZdczoS5VOZebZ0wPlN++gjbKKkJB344MvZIAQ2W8HaHoKCAkQ8IpMdOmjUBiaPtKX4tVySufg/Rz51z/Z6bzyPQr23uFaRbPLbyA1jtFsrmJXakgHza742vEEoVzVAfN1vvWkMZtpbQ==
  template:
    metadata:
      name: mks-oneclick-v3-1-40
      namespace: default

