apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: a1
  project: akshay-2
spec:
  active: true
  cluster:
    name: akshay-mks-preview
  config:
    concurrency: 55
    environment:
      numWorkers: 15
    kubernetes:
      limits:
        cpu: 255m
        memory: 1Gi
  type: Cluster
  version: r4.2.0
