apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: input
  project: akshay
spec:
  envs:
  - key: ev1
    options:
      override:
        multiSelect: true
        restrictedValues:
        - ev11
        - ev12
        - ev13
        type: restricted
    value: ev11
  - key: ev2
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          ev21: ev21
          ev22: ev22
          ev23: ev23
        type: restricted_key_values
    value: ev21
  variables:
  - name: iv1
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedValues:
        - a
        - b
        - c
        type: restricted
    valueType: text
  - name: iv2
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedKeyValues:
          rkv1: one
          rkv2: two
          rkv3: three
        type: restricted_key_values
    valueType: text
  - name: iv3
    options:
      displayMetadata: {}
      override:
        restrictedValues:
        - "11"
        - "1"
        - "111"
        type: restricted
    valueType: expression
  - name: iv4
    options:
      displayMetadata: {}
      override:
        restrictedKeyValues:
          exp1: '#{environment.id}#'
          exp2: '#{environment.name}#'
          exp3: '#{environment.project.name}#'
        type: restricted_key_values
    valueType: expression
