apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: input
  project: akshay
spec:
  variables:
  - name: iv1
    options:
      override:
        multiSelect: true
        restrictedValues:
        - a
        - b
        - c
        type: restricted
    valueType: text
  - name: iv2
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedKeyValues:
          rkv1: one
          rkv2: two
          rkv3: three
        type: restricted_key_values
    valueType: text
  - name: iv3
    options:
      override:
        restrictedValues:
        - "11"
        - "1"
        - "111"
        type: restricted
    valueType: text
