apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  description: Migration from Terraform
  name: bcm-python-provisioning-test
  project: system-catalog
spec:
  config:
    function:
      cpuLimitMilli: "4000"
      image: ops-console.gpupaas-qc.dev.rafay-edge.net/rafay/bcm-node-provisioning:v3.1.39-11
      language: python
      memoryLimitMb: "2000"
      name: python-node-provisioning-test
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    timeoutSeconds: 7200
    type: function
  inputs:
  - data:
      variables:
      - name: action
        options:
          override:
            type: allowed
          required: true
        value: $(trigger.payload.type)$
        valueType: expression
    name: input
