apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: naveet-neysa
  project: system-catalog
spec:
  config:
    function:
      image: registry.dev.rafay-edge.net/paas-workflow-handler-outputfilter:v2
      imagePullCredentials:
        password: testbed123
        username: pranay.jugge@rafay.co
      language: python
      name: handle
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    type: function
