apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  annotations:
    eaas.envmgmt.io/releaseversion: v3.1.37
  name: nim
  project: system-catalog
spec:
  config:
    container:
      image: ops-console.gpupaas-qc.dev.rafay-edge.net/rafay/rafay-nim:1.0
      kubeOptions:
        securityContext:
          readOnlyRootFileSystem: false
    timeoutSeconds: 3600
    type: container
  inputs:
  - data:
      envs:
      - key: CACHE_STORAGE_ACCESS_MODE
        value: $(current.input.cache_storage_access_mode)$
      - key: SERVICE_PORT
        value: $(current.input.service_port)$
      - key: GRPC_PORT
        value: $(current.input.grpc_port)$
      - key: ENV_VARS
        value: $(current.input.env_vars)$
      - key: DEVICE_DETAILS
        value: $(current.input.device_details)$
      - key: CACHE_STORAGE_SIZE
        value: $(current.input.cache_storage_size)$
      - key: CACHE_STORAGE_CLASS_NAME
        value: $(current.input.cache_storage_class_name)$
      - key: CACHE_ENGINE
        value: $(current.input.cache_engine)$
      - key: ENABLE_CACHE
        value: $(current.input.enable_cache)$
      - key: STORAGE_SIZE
        value: $(current.input.storage_size)$
      - key: GPU_LIMIT
        value: $(current.input.gpu_limit)$
      - key: MEMORY_LIMIT
        value: $(current.input.memory_limit)$
      - key: CPU_LIMIT
        value: $(current.input.cpu_limit)$
      - key: NODE_SELECTOR
        value: $(current.input.node_selector)$
      - key: STORAGE_CLASS_NAME
        value: $(current.input.storage_class_name)$
      - key: MODEL_NAME
        value: $(current.input.model_name)$
      - key: NGC_API_KEY
        value: $(current.input.ngc_api_key)$
      - key: VAR_kubeconfig
        value: $(current.input.kubeconfig)$
      - key: MODEL_INFO
        value: $(json.Marshal(current.input.model_info))$
      - key: NAMESPACE
        value: $(environment.name)$
      - key: DOMAIN
        value: $(current.input.domain)$
      - key: ACTION
        options:
          override:
            type: notallowed
        value: $(trigger.payload.action)$
    name: wfh-context
