apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  annotations:
    eaas.envmgmt.io/releaseversion: v3.1.40
  name: push-paas-events-v3-1-40
  project: system-catalog
spec:
  config:
    function:
      image: registry.rafay-edge.net/rafay/push-paas-events:v3.1.40-2
      language: python
      name: push-paas-events
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    type: function
  inputs:
  - name: previous-run
  - name: rafay-creds
  - name: billing-config
  sharing:
    enabled: true
    projects:
    - name: '*'
