apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  annotations:
    eaas.envmgmt.io/releaseversion: v3.1.40
  name: vmaas-storage-workflow-v3-1-40
  project: system-catalog
spec:
  config:
    function:
      image: registry.rafay-edge.net/rafay/vmaas-storage:v3.1.40-2
      language: python
      name: vmaas-storage-workflow
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    timeoutSeconds: 300
    type: function
  inputs:
  - data:
      variables:
      - name: action
        options:
          override:
            type: notallowed
        value: |-
          ## script begin ##
          def eval(**ctx):
            action_name = ctx["trigger"]["payload"].get("action_name")
            if action_name:
              return action_name
            return ctx["trigger"]["payload"].get("action")
          ## script end ##
        valueType: expression
    name: action
  sharing:
    enabled: true
    projects:
    - name: '*'
