apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  annotations:
    eaas.envmgmt.io/releaseversion: v3.1.39
  name: vmaas-node-onboarding-workflow-v3-1-39
  project: system-catalog
spec:
  config:
    function:
      cpuLimitMilli: "500"
      image: ops-console.gpupaas-qc.dev.rafay-edge.net/rafay/vmaas-node-onboarding:v3.1.39-13
      language: python
      memoryLimitMb: "1024"
      name: vmaas-node-onboarding
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    timeoutSeconds: 1200
    type: function
  inputs:
  - data:
      variables:
      - name: action
        options:
          override:
            type: notallowed
        value: |-
          ## script begin ##
          def eval(**ctx):
            action_name = ctx["trigger"]["payload"].get("action_name")
            if action_name:
              return action_name
            return ctx["trigger"]["payload"].get("action")
          ## script end ##
        valueType: expression
    name: input
  sharing:
    enabled: true
    projects:
    - name: '*'
