apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: cc-multi
  project: akshay-2
spec:
  envs:
  - key: env1
    options:
      override:
        multiSelect: true
        restrictedValues:
        - env1val1
        - env1val2
        - env1val3
        type: restricted
    value: env1val1
  - key: env2
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          key1: env2val1
          key2: env2val2
          key3: env2val3
        type: restricted_key_values
    value: '["key1","key2"]'
  variables:
  - name: iv1
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedValues:
        - val1
        - val2
        - val3
        type: restricted
    value: val1
    valueType: text
  - name: iv2
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedValues:
        - '#{environment.id}#'
        - '#{environment.name}#'
        - '#{organization.name}#'
        type: restricted
    value: '#{environment.id}#'
    valueType: expression
  - name: iv3
    options:
      override:
        multiSelect: true
        restrictedValues:
        - val1
        - val2
        - val3
        type: restricted
    valueType: json
  - name: iv4
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          key1: val1
          key2: val2
          key3: val3
        type: restricted_key_values
    value: '["key1","key2"]'
    valueType: text
  - name: iv5
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          key1: '#{environment.name}#'
          key2: '#{environment.id}#'
          key3: '#{organization.name}#'
        type: restricted_key_values
    value: '["key1","key2"]'
    valueType: expression
  - name: iv6
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          key1: val1
          key2: val2
          key3: val3
        type: restricted_key_values
    valueType: json
  - name: normal
    options:
      override:
        restrictedValues:
        - a1
        - a2
        - a3
        type: restricted
    value: a1
    valueType: text
