apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mks-oneclick-v3-1-39
  namespace: default
spec:
  encryptedData:
    registry_credentials: AQAFaLj8AKFDeGBAaP+8SBDe2BldCViVP92sxrxsBUSJsVL6sl7zn1Uec+80QnijG9vCXPuOOqd8UaNqk6VKBYJXtauh+JH1dG6pe6K7Xp0m+gNcxVKpDobRbKxmQxz6X+HJKKqGPmd5THnuhusEQNogmeqM022t+CD2G2hQ+dUPOqcR3UdW35Ld0CPfs0U7LlB+pDpKVPmMvo9a/flp0GXWA3VeWgBVFxsaoCMdo+JcqU59lAR44QtsNtBDQpaX75/WUXhic9IKIA1imiZ3dxo6IphzcH+tbxk51J4auEXHs2tb1R7+nPylZ9KhO7LZftbNK+ZjDEX5DpBYdI00/kX8zGCWtg4ZsskEvygvjPoVzQ==
  template:
    metadata:
      name: mks-oneclick-v3-1-39
      namespace: default

