apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: env2
  project: akshay
spec:
  agents:
  - name: agent-kr-tb
  template:
    name: et1
    version: v1
    versionState: unspecified
  variables:
  - name: iv3
    options:
      override:
        multiSelect: true
        restrictedValues:
        - "11"
        - "1"
        - "111"
        - "1111"
        type: restricted
    value: '["1","1111"]'
    valueType: text
  - name: iv1
    options:
      override:
        multiSelect: false
        restrictedValues:
        - a
        - b
        - c
        type: restricted
    value: "c"
    valueType: text
  - name: iv2
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedKeyValues:
          rkv1: one
          rkv2: two
          rkv3: three
        type: restricted_key_values
    value: '["rkv1","rkv3"]'
    valueType: text
