apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: env234
  project: akshay
spec:
  agents:
  - name: agent-kr-tb
  template:
    name: et1
    version: v1
    versionState: unspecified
  variables:
  - name: iv3
    options:
      override:
        multiSelect: true
        restrictedValues:
        - "111"
        - "1"
        - "11"
        type: restricted
    value: '["11","1","111"]'
    valueType: text
  - name: iv-rv-e
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedKeyValues:
          exp1: '#{environment.id}#'
          exp2: '#{environment.name}#'
          exp3: '#{environment.project.name}#'
        type: restricted_key_values
    value: '["exp1","exp2","exp3"]'
    valueType: expression
  - name: iv-r-j
    options:
      override:
        multiSelect: true
        restrictedValues:
        - a
        - b
        - c
        type: restricted
    value: '["c","b","a"]'
    valueType: json
  - name: iv-rv-j
    options:
      override:
        multiSelect: true
        restrictedKeyValues:
          a: A
          b: B
          c: C
        type: restricted_key_values
    value: '["c","b","a"]'
    valueType: json
  - name: iv-r-t
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedValues:
        - a
        - b
        - c
        type: restricted
    value: '["a","b","c"]'
    valueType: text
  - name: iv-rv-t
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedKeyValues:
          rkv1: one
          rkv2: two
          rkv3: three
        type: restricted_key_values
    value: '["rkv1","rkv2","rkv3"]'
    valueType: text
  - name: iv-r-e
    options:
      displayMetadata: {}
      override:
        multiSelect: true
        restrictedValues:
        - "11"
        - "1"
        - "111"
        type: restricted
    value: '["1","11","111"]'
    valueType: expression
