apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mks-oneclick-test
  namespace: default
spec:
  encryptedData:
    registry_credentials: AQA+y+/7nHcwUzdYNgSzp0N7ZwqG2ICLkBPsR0NHb1oh/bLw1lnYSuUwyxrDQS4cLeM1OSCnVoJUPrUUkdzSrskK0jRss2pxUf3TRezuw2kl2wQIXFxrNRdSfP1oeaw0LOv6bhqc6wZTiAik0N08Y966UZdono7n4txhBgoOAYcjPkoq2OAR5I7IRw+4B0vUUtCOgXjLlyAJK69EWtdW93SlQEoangIlaVFs0bKn8L904r1Rb3HtGVdl2iy4L4zaYVsnQyFGyDU2+WSaiNZvoa+yCezSTl4zagY9Jc0d3Mg9BpZ0pl6RJh37P24z/AHXcpyBKt8fdlO1GSdsKyIjeRyMaEdP7aeDn9OxwN7AigOOlw==
  template:
    metadata:
      name: mks-oneclick-test
      namespace: default

