apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-stable-helm
  project: eaas-git-sync-parallel
spec:
  endpoint: https://charts.helm.sh/stable
  options: {}
  type: Helm
